### ISSUE TITLE
Implicit add parameters for partition columns

### ISSUE THREAD

**Issue by aersam** [bmsuisse/lakeapi#43]
Filters on partitions are always fast, therefore we should enable them by default. You could still hide those be giving them an empty operators array:

```yml
params:
      - name: partition_col
        operators: []
```
